apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://192.168.49.2:8443
    insecure-skip-tls-verify: true
  name: k8s-cluster

users:
- name: jenkins-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImM3WndZUExkRkduMkxZZjhnX0xvU0hrZFFRbG91S1IwVm5wREswOTJKMGsifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzYzNDI4MjY4LCJpYXQiOjE3NjM0MjQ2NjgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMTk2MjcyYWEtYmMyZi00NTljLTlmOTItYmFjMDMxODZjMDY3Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJqZW5raW5zLXNhIiwidWlkIjoiYWYzYzdlYTEtZjVhMS00YTg4LTgxYWMtNjQ0Y2IzOTFmNmJhIn19LCJuYmYiOjE3NjM0MjQ2NjgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpqZW5raW5zLXNhIn0.cpxAjm3Yk4L7J-sDKyQI_9UKwb-kVw-e4R_m3RwQPF3Hnd7pvG4ydRrsQXp8vGbwGz2wAYJYABgRH5wnf_-orqO1E-LGVrFOARq-P-4vV5lFQhIioRYRk130QMhivnlTFDIGk7q8siJoEhMPsFJD7KyXf6_DQF7hB1Nx_AltiGwwMQ2JRMgI5qo_lPkRnS458ltd07ng5lbjjaR8fWY4dlRve9tQYKeS0ga3awztIvvvrsE2S9iJ93cXlu6T88KeOn3NRERAmk9nlvTidnAtITmWus0HYO2NRj5iAF0PdmYXA_NoM0Q28h0u5ICBqoKEH8gjYYOuDa_VfuSwmaVmIA

contexts:
- context:
    cluster: k8s-cluster
    namespace: ivolve
    user: jenkins-sa
  name: jenkins-context

current-context: jenkins-context

