apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: pod-reader-jenkins-sa-binding
  namespace: ivolve
subjects:
- kind: ServiceAccount
  name: jenkins-sa
roleRef:
  kind: Role 
  name: pod-reader 
  apiGroup: rbac.authorization.k8s.io

